classDiagram
  class Titulo {
    +tipo "movie | tv"
    +nombre
    +sinopsis
    +portadaUrl
    +anioEstreno
    +anioFin
    +duracion "solo peliculas"
    +estadoRenovacionTMDB "solo series"
    +proximoEpisodioFecha "solo series"
    +director
    +guionista
    +pais
    +idiomaOriginal
    +popularidad
    +popularidadPercentil
    +voteAverageTMDB
    +voteCountTMDB
    +ratingUnificado
  }

  class Actor {
    +nombre
  }

  class TituloElenco {
    +personaje
    +orden
  }
  Titulo "1" --> "*" TituloElenco : tiene elenco
  Actor "1" --> "*" TituloElenco : participa en

  class Genero {
    +nombre
  }
  Titulo "*" --> "*" Genero : tiene

  class Temporada {
    +numero
    +sinopsis
    +fechaEstreno
  }
  Titulo "1" --> "*" Temporada : temporadas (solo si tipo=tv)

  class Episodio {
    +numero
    +nombre
    +fechaEstreno
    +duracion
  }
  Temporada "1" --> "*" Episodio : tiene

  class Usuario {
    +nombreUsuario
    +passwordHash
    +pais
    +ciudad
    +descripcion
    +fechaRegistro
    +avatarUrl
    +esAdmin
  }

  class EstadoUsuarioTitulo {
    +favorito
    +fechaFavorito
    +estado "watchlist | siguiendo | vista | null"
    +fechaEstado
  }
  Usuario "1" --> "*" EstadoUsuarioTitulo : marca
  Titulo "1" --> "*" EstadoUsuarioTitulo : tiene

  class EpisodioVisto {
    +fechaVisto
  }
  Usuario "1" --> "*" EpisodioVisto : registra
  Episodio "1" --> "*" EpisodioVisto : referencia

  class Resena {
    +puntaje
    +texto
    +fecha
    +autorTMDB
    +tmdbReviewId
  }
  Titulo "1" --> "*" Resena : recibe
  Usuario "0..1" --> "*" Resena : escribe
